import {Coins} from 'lucide-react';
import type {ReactNode} from 'react';

const CHIP_COLORS: Record<number, {button: string; face: string; edge: string; text: string; accent: string}> = {
  1: {button: 'border-zinc-200 bg-zinc-50 text-zinc-900 hover:bg-white', face: 'bg-zinc-100', edge: 'border-zinc-300', text: 'text-zinc-900', accent: 'bg-zinc-900/70'},
  5: {button: 'border-rose-300 bg-rose-500 text-white hover:bg-rose-400', face: 'bg-rose-500', edge: 'border-rose-200', text: 'text-white', accent: 'bg-white/80'},
  10: {button: 'border-sky-300 bg-sky-500 text-white hover:bg-sky-400', face: 'bg-sky-500', edge: 'border-sky-200', text: 'text-white', accent: 'bg-white/80'},
  25: {button: 'border-emerald-300 bg-emerald-500 text-white hover:bg-emerald-400', face: 'bg-emerald-500', edge: 'border-emerald-200', text: 'text-white', accent: 'bg-white/80'},
  50: {button: 'border-amber-200 bg-zinc-900 text-amber-200 hover:bg-zinc-800', face: 'bg-zinc-900', edge: 'border-amber-200/80', text: 'text-amber-200', accent: 'bg-amber-200/80'},
};

function chipLabel(value: number): string {
  return `$${value}`;
}

export function SummaryTile({label, value, color}: {label: string; value: string; color: string}) { return <div className="rounded-2xl border border-white/10 bg-black/20 p-3"><p className="text-[10px] font-bold uppercase tracking-[0.28em] text-zinc-500">{label}</p><p className={`mt-2 text-lg font-black ${color}`}>{value}</p></div>; }
export function InlineStat({label, value}: {label: string; value: string}) { return <div className="flex items-center justify-between gap-3"><span className="text-zinc-500">{label}</span><span className="font-mono text-white">{value}</span></div>; }
export function ProgressRow({label, count, total, color}: {label: string; count: number; total: number; color: string}) { const width = `${Math.min((count / total) * 100, 100)}%`; return <div><div className="mb-1 flex items-center justify-between text-sm"><span className="text-zinc-300">{label}</span><span className="font-mono text-white">{count}</span></div><div className="h-2 rounded-full bg-white/10"><div className={`h-2 rounded-full ${color}`} style={{width}} /></div></div>; }
export function Metric({label, value, accent}: {label: string; value: string; accent: string}) { return <div className="text-right"><p className="text-[10px] uppercase tracking-[0.3em] text-zinc-500">{label}</p><p className={`mt-1 font-mono text-sm font-bold ${accent}`}>{value}</p></div>; }
export function ToggleRow({label, desc, checked, onToggle}: {label: string; desc: string; checked: boolean; onToggle: () => void}) { return <button type="button" onClick={onToggle} className="flex w-full items-center justify-between gap-4 rounded-2xl border border-white/10 bg-white/5 p-4 text-left transition hover:bg-white/10"><div><p className="text-sm font-black text-white">{label}</p><p className="mt-1 text-sm text-zinc-400">{desc}</p></div><span className={`rounded-full px-3 py-1 text-xs font-black ${checked ? 'bg-emerald-500 text-black' : 'bg-white/10 text-zinc-400'}`}>{checked ? 'ON' : 'OFF'}</span></button>; }
export function IconButton({icon, onClick}: {icon: ReactNode; onClick?: () => void}) { return <button type="button" onClick={onClick} className="rounded-full border border-white/8 bg-white/5 p-2 text-zinc-300 transition hover:bg-white/10 hover:text-white">{icon}</button>; }
export function Badge({icon, label, value, tone}: {icon: ReactNode; label: string; value: string; tone: 'slate' | 'emerald'}) { const toneClass = tone === 'emerald' ? 'border-emerald-400/30 bg-emerald-500/15 text-emerald-300' : 'border-white/10 bg-black/30 text-zinc-300'; return <div className={`flex items-center gap-2 rounded-full border px-3 py-1.5 backdrop-blur ${toneClass}`}>{icon}<span className="text-[10px] font-bold uppercase tracking-[0.28em]">{label}</span><span className="rounded bg-black/30 px-1.5 py-0.5 font-mono text-[10px] text-white">{value}</span></div>; }
export function EmptySlot({label}: {label: string}) { return <div className="flex min-h-32 items-center justify-center rounded-[1.4rem] border border-dashed border-white/10 bg-black/10 px-4 text-center text-sm text-zinc-400">{label}</div>; }
export function BettingChipRack({chips, totalLabel, onRemoveChip}: {chips: number[]; totalLabel: string; onRemoveChip?: (chipIndex: number) => void}) { return <div className="rounded-[1.4rem] border border-amber-300/20 bg-black/25 p-4"><div className="mb-4 flex items-center justify-between gap-3"><p className="text-[11px] font-bold uppercase tracking-[0.28em] text-amber-300">Bet On Table</p><div className="rounded-full border border-white/10 bg-black/30 px-3 py-1.5 font-mono text-sm font-bold text-white">{totalLabel}</div></div><div className="flex min-h-20 flex-wrap items-end gap-2">{chips.map((chip, index) => <div key={`${chip}-${index}`} className="-ml-1 first:ml-0"><CasinoChip value={chip} label={chipLabel(chip)} onClick={onRemoveChip ? () => onRemoveChip(index) : undefined} /></div>)}</div></div>; }
export function CasinoChip({value, label, compact = false, onClick}: {key?: string | number; value: number; label: string; compact?: boolean; onClick?: () => void}) { const palette = CHIP_COLORS[value]; const sizeClass = compact ? 'h-12 w-12 text-[10px]' : 'h-16 w-16 text-xs'; const innerClass = compact ? 'h-8 w-8' : 'h-10 w-10'; return <button type="button" onClick={onClick} disabled={!onClick} className={`relative flex ${sizeClass} items-center justify-center rounded-full border-[3px] shadow-[0_10px_24px_rgba(0,0,0,0.35)] ${palette.face} ${palette.edge} ${palette.text} ${onClick ? 'cursor-pointer transition hover:-translate-y-1 hover:brightness-110' : 'cursor-default'}`}><div className="absolute inset-[5px] rounded-full border border-dashed border-white/50" /><div className={`absolute ${innerClass} rounded-full border border-white/35 bg-black/10`} /><div className={`absolute inset-x-3 top-2 h-1 rounded-full ${palette.accent}`} /><div className={`absolute inset-x-3 bottom-2 h-1 rounded-full ${palette.accent}`} /><span className="relative z-10 font-black tracking-[0.08em]">{label}</span></button>; }
export function ChipButton({value, label, onClick, disabled, subtle = false}: {key?: string | number; value?: number; label: string; onClick: () => void; disabled: boolean; subtle?: boolean}) { if (subtle) return <button type="button" onClick={onClick} disabled={disabled} className={`rounded-full px-4 py-2 text-sm font-black tracking-[0.12em] transition ${disabled ? 'cursor-not-allowed bg-white/8 text-zinc-500' : 'border border-white/10 bg-black/20 text-zinc-100 hover:bg-white/8'}`}>{label}</button>; const palette = CHIP_COLORS[value ?? 1]; return <button type="button" onClick={onClick} disabled={disabled} className={`group flex h-20 w-20 flex-col items-center justify-center rounded-full border-[3px] transition ${disabled ? 'cursor-not-allowed border-white/10 bg-white/8 text-zinc-500 opacity-40' : `${palette.button} shadow-[0_16px_34px_rgba(0,0,0,0.32)] hover:-translate-y-1`}`}><Coins className="h-4 w-4" /><span className="mt-1 text-base font-black leading-none">{label}</span></button>; }
export function ActionButton({label, sub, onClick, disabled = false}: {label: string; sub: string; onClick: () => void; disabled?: boolean}) { return <button type="button" onClick={onClick} disabled={disabled} className={`rounded-2xl border px-4 py-4 text-center transition ${disabled ? 'cursor-not-allowed border-white/6 bg-white/4 opacity-35' : 'border-white/10 bg-black/20 hover:border-emerald-400/30 hover:bg-white/8'}`}><p className="text-sm font-black uppercase tracking-[0.24em] text-white">{label}</p><p className="mt-1 text-[10px] font-bold uppercase tracking-[0.3em] text-zinc-500">{sub}</p></button>; }
export function Panel({title, icon, badge, children}: {title: string; icon: ReactNode; badge?: string; children: ReactNode}) { return <section className="rounded-[1.75rem] border border-white/8 bg-black/25 p-6 shadow-[0_20px_60px_rgba(0,0,0,0.32)] backdrop-blur-xl"><div className="mb-6 flex items-center justify-between gap-3"><div className="flex items-center gap-2">{icon}<h2 className="text-sm font-black uppercase tracking-[0.24em] text-white">{title}</h2></div>{badge ? <span className="rounded-full border border-emerald-400/20 bg-emerald-500/10 px-2 py-1 text-[10px] font-bold uppercase tracking-[0.28em] text-emerald-300">{badge}</span> : null}</div><div className="space-y-4">{children}</div></section>; }
export function SmallMetric({label, value, color}: {label: string; value: string; color: string}) { return <div className="rounded-2xl border border-white/8 bg-white/4 p-3"><p className="text-[10px] font-bold uppercase tracking-[0.28em] text-zinc-500">{label}</p><p className={`mt-2 font-mono text-sm font-bold ${color}`}>{value}</p></div>; }
export function StatRow({label, value, color, multiline = false}: {label: string; value: string; color: string; multiline?: boolean}) { return <div className={`flex justify-between gap-4 border-b border-white/6 pb-4 last:border-b-0 last:pb-0 ${multiline ? 'items-start' : 'items-center'}`}><span className="text-xs font-bold uppercase tracking-[0.3em] text-zinc-500">{label}</span><span className={`font-mono text-sm font-bold ${color} ${multiline ? 'max-w-[13rem] text-right leading-6' : ''}`}>{value}</span></div>; }
export function Chip({label, active = false}: {label: string; active?: boolean}) { return <span className={`rounded-full px-2.5 py-1 ${active ? 'bg-emerald-500/15 text-emerald-300' : 'bg-white/6 text-zinc-300'}`}>{label}</span>; }
